# Generated by Django 3.2.3 on 2021-06-24 09:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pricewatcher", "0002_auto_20210624_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="geonameid",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
