# Generated by Django 3.2.3 on 2021-06-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricewatcher", "0003_alter_city_geonameid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="geoiplocation",
            unique_together={("ip", "longitude", "latitude", "postal_code", "city")},
        ),
    ]
