# Generated by Django 3.2.3 on 2021-06-24 10:11

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pricewatcher", "0004_alter_geoiplocation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesample",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricewatcher.geoiplocation",
            ),
        ),
    ]
