# Generated by Django 3.2.3 on 2021-07-27 13:57

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pricewatcher", "0005_pricesample_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.RunSQL(
            sql="INSERT INTO pricewatcher_browsermake(name) SELECT distinct(name) from pricewatcher_browser;"
        ),
        migrations.CreateModel(
            name="BrowserRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.IntegerField(choices=[(1, "Addon / Webstore")], default=1)),
                ("url", models.URLField(max_length=2083)),
                ("default", models.BooleanField(default=False)),
                (
                    "browser_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pricewatcher.browsermake"
                    ),
                ),
            ],
        ),
    ]
