# Generated by Django 4.0.5 on 2022-06-28 16:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pricewatcher", "0006_browsermake_browserredirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="scraper",
            field=models.TextField(default="require $noop;\nreturn $noop;\n", max_length=20000),
            preserve_default=False,
        ),
    ]
