# Generated by Django 3.2.3 on 2021-06-14 15:12

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultvalue",
            name="field_definition",
        ),
        migrations.AddField(
            model_name="fielddefinition",
            name="default_value",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="registration.defaultvalue",
            ),
        ),
    ]
