# Generated by Django 3.2.3 on 2021-06-14 15:15

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_auto_20210614_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fielddefinition",
            name="default_value",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="registration.defaultvalue",
            ),
        ),
    ]
