# Generated by Django 3.2.3 on 2021-06-24 09:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_fielddefinition_default_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fielddefinition",
            name="widget",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Auto"),
                    (1, "Radio Buttons"),
                    (2, "Conditional Multi Field"),
                    (3, "Multiple Choice"),
                    (4, "Text area"),
                ],
                default=0,
                help_text="how to render the field",
            ),
        ),
    ]
